export const PERMISSIONS = {
  doctorOnboardingViewOwn: 'DoctorOnboarding.ViewOwn',
  doctorsViewAll: 'Doctors.ViewAll',
  doctorsViewDetails: 'Doctors.ViewDetails',
  doctorsApprove: 'Doctors.Approve',
  doctorsReject: 'Doctors.Reject',
  doctorsSuspend: 'Doctors.Suspend',
  doctorsReactivate: 'Doctors.Reactivate',
  superAdminsViewAll: 'SuperAdmins.ViewAll',
  superAdminsViewDetails: 'SuperAdmins.ViewDetails',
  superAdminsCreate: 'SuperAdmins.Create',
  superAdminsUpdate: 'SuperAdmins.Update',
  superAdminsActivate: 'SuperAdmins.Activate',
  superAdminsDeactivate: 'SuperAdmins.Deactivate',
  superAdminsDelete: 'SuperAdmins.Delete',
  superAdminsRestore: 'SuperAdmins.Restore',
  rolesView: 'Roles.View',
  permissionsView: 'Permissions.View',
  rolePermissionsManage: 'RolePermissions.Manage',
} as const;
