export const PERMISSIONS = {
  doctorOnboardingViewOwn: 'DoctorOnboarding.ViewOwn',
  doctorsViewAll: 'Doctors.ViewAll',
  doctorsViewDetails: 'Doctors.ViewDetails',
  doctorsApprove: 'Doctors.Approve',
  doctorsReject: 'Doctors.Reject',
  doctorsSuspend: 'Doctors.Suspend',
  doctorsReactivate: 'Doctors.Reactivate',
  superAdminsViewAll: 'SuperAdmins.ViewAll',
  superAdminsViewDetails: 'SuperAdmins.ViewDetails',
  superAdminsCreate: 'SuperAdmins.Create',
  superAdminsUpdate: 'SuperAdmins.Update',
  superAdminsActivate: 'SuperAdmins.Activate',
  superAdminsDeactivate: 'SuperAdmins.Deactivate',
  superAdminsDelete: 'SuperAdmins.Delete',
  superAdminsRestore: 'SuperAdmins.Restore',
  rolesView: 'Roles.View',
  permissionsView: 'Permissions.View',
  rolePermissionsManage: 'RolePermissions.Manage',
  specializationsView: 'Specializations.View',
  specializationsCreate: 'Specializations.Create',
  specializationsUpdate: 'Specializations.Update',
  specializationsActivate: 'Specializations.Activate',
  specializationsDeactivate: 'Specializations.Deactivate',
  specializationsDelete: 'Specializations.Delete',
  specializationsRestore: 'Specializations.Restore',
  doctorSpecializationsViewOwn: 'DoctorSpecializations.ViewOwn',
  doctorSpecializationsSubmitOwn: 'DoctorSpecializations.SubmitOwn',
  doctorSpecializationsResubmitOwn: 'DoctorSpecializations.ResubmitOwn',
  doctorPracticeLocationViewOwn: 'DoctorPracticeLocation.ViewOwn',
  doctorPracticeLocationManageOwn: 'DoctorPracticeLocation.ManageOwn',
  doctorSpecializationRequestsViewAll: 'DoctorSpecializationRequests.ViewAll',
  doctorSpecializationRequestsViewDetails: 'DoctorSpecializationRequests.ViewDetails',
  doctorSpecializationRequestsAdjust: 'DoctorSpecializationRequests.Adjust',
  doctorSpecializationRequestsRequestModification:
    'DoctorSpecializationRequests.RequestModification',
  doctorSpecializationRequestsApprove: 'DoctorSpecializationRequests.Approve',
  doctorSpecializationRequestsReject: 'DoctorSpecializationRequests.Reject',
} as const;
