import {
  MedicalCatalogResponse,
  DiagnosticImportBatchResponse,
  MedicalCatalogRequestResponse,
} from '../../domains/medical-catalog';
export const catalogFixture: MedicalCatalogResponse = {
  catalogId: 'catalog',
  source: 'Wasla',
  status: 'Active',
  loincCode: null,
  nameEn: 'Synthetic test',
  nameAr: 'Synthetic Arabic fixture',
  officialNameEn: 'Official name',
  officialNameAr: null,
  externalStatus: null,
  sourceVersion: null,
  isCommonOrder: false,
  presentation: {
    displayNameEn: 'Synthetic test',
    displayNameAr: 'Synthetic Arabic fixture',
    aliasesEn: null,
    aliasesAr: null,
    internalNote: null,
  },
  sourceDataJson: null,
  attributesJson: null,
  mergedIntoId: null,
  rowVersion: 'catalog-rv',
  capabilities: { canEdit: true, canActivate: false, canDeactivate: true, canMerge: true },
  history: [],
};
export const importFixture: DiagnosticImportBatchResponse = {
  batchId: 'batch',
  sourceVersion: 'v1',
  originalFileName: 'catalog.csv',
  fileSha256: 'synthetic',
  uploadedByUserId: 'manager',
  uploadedAtUtc: '2026-10-07T09:00:00Z',
  status: 'Staged',
  totalRecords: 1,
  counts: {
    New: 1,
    Unchanged: 0,
    Changed: 0,
    ArabicAdded: 0,
    ArabicChanged: 0,
    ExternalStatusChanged: 0,
    PossibleConflict: 0,
    Skipped: 0,
  },
  appliedByUserId: null,
  appliedAtUtc: null,
  rowVersion: 'batch-rv',
  capabilities: { canApply: true, canDiscard: true },
};
export const catalogRequestFixture: MedicalCatalogRequestResponse = {
  requestId: 'catalog-request',
  requestedByDoctorId: 'doctor',
  name: 'Synthetic missing test',
  specimen: 'Blood',
  catalogClarificationNote: 'Catalog note',
  status: 'Pending',
  canonicalCatalogId: null,
  reasonType: null,
  reviewReason: null,
  createdAtUtc: '2026-10-07T09:00:00Z',
  rowVersion: 'review-rv',
  capabilities: { canEdit: true, canRequestMoreInfo: true, canApprove: true, canReject: true },
  history: [],
  canonicalCatalog: catalogFixture,
};
