import {
  DiagnosticRequestStateResponse,
  DiagnosticResultResponse,
  DiagnosticSubmissionResponse,
} from '../../domains/diagnostics';
export const diagnosticResult: DiagnosticResultResponse = {
  resultId: 'result',
  requestId: 'request',
  rowVersion: 'result-rv',
  currentVersionNumber: 1,
  capabilities: { canCorrect: true, canVoid: true },
  current: {
    versionId: 'version',
    versionNumber: 1,
    status: 'Finalized',
    externalProviderName: 'Synthetic laboratory',
    externalReportDate: '2026-10-07',
    originallyUploadedBy: 'Doctor',
    originallyUploadedAtUtc: '2026-10-07T09:00:00Z',
    reviewedByDoctorId: 'doctor',
    reviewedAtUtc: '2026-10-07T09:00:00Z',
    coveredItemIds: ['item'],
    attachments: [
      {
        attachmentId: 'attachment',
        originalFileName: 'report.pdf',
        contentType: 'application/pdf',
        sizeBytes: 10,
        sha256: 'synthetic',
        uploadedAtUtc: '2026-10-07T09:00:00Z',
        kind: 'Report',
      },
    ],
    correctionReason: 'Internal correction reason',
    voidReason: 'Internal void reason',
  },
};
export const diagnosticRequest: DiagnosticRequestStateResponse = {
  requestId: 'request',
  medicalEncounterId: 'encounter',
  doctor: { id: 'doctor', nameAr: 'Synthetic Arabic fixture', nameEn: 'Synthetic doctor' },
  practice: { id: 'practice', nameAr: 'Synthetic Arabic fixture', nameEn: 'Synthetic clinic' },
  origin: 'DuringEncounter',
  status: 'Requested',
  rowVersion: 'request-rv',
  patientInstructions: 'Patient instructions',
  requestedAtUtc: '2026-10-07T09:00:00Z',
  postVisitReason: 'Internal post-visit reason',
  capabilities: { canManageDraft: true, canCancelRemaining: true, canUploadResult: true },
  items: [
    {
      itemId: 'item',
      nameArSnapshot: 'Synthetic Arabic fixture',
      nameEnSnapshot: 'Synthetic test',
      loincCodeSnapshot: 'synthetic',
      modalitySnapshot: null,
      anatomicLocationSnapshot: null,
      lateralitySnapshot: null,
      doctorInstructions: 'Internal doctor instructions',
      status: 'Requested',
      cancellationReason: null,
      catalogId: 'catalog',
      catalogRequestId: null,
      capabilities: { canEdit: true, canRemove: true, canCancel: true, hasCurrentResult: false },
    },
  ],
  currentResults: [diagnosticResult],
  submissions: [],
};
export const diagnosticSubmission: DiagnosticSubmissionResponse = {
  submissionId: 'submission',
  requestId: 'request',
  status: 'PendingReview',
  externalProviderName: 'Synthetic laboratory',
  externalReportDate: '2026-10-07',
  patientNote: 'Patient note',
  patientVisibleReason: null,
  acceptedResultId: null,
  submittedAtUtc: '2026-10-07T09:00:00Z',
  rowVersion: 'submission-rv',
  attachments: diagnosticResult.current.attachments,
  capabilities: { canWithdraw: true, canAccept: true, canReject: true },
};
